### ISSUE TITLE
General questions about the Topic 2023

### ISSUE THREAD

**Issue by theodorosploumis** [serrestech/hackathon-topic#1]
This is the default issue for **general questions** regarding the 2023 #SerresHack topic.

**Comment by ErminaTrontzou** [comment]
Can a shape be used more than once in the same solution?

**Comment by theodorosploumis** [comment]
> Can a shape be used more than once in the same solution?

**No**. Except if the Task says the opposite.

**Comment by MaciejRtk95** [comment]
That would be A.10]? Does the task mean that the user should be able to specify for example a limit of "2 Ls and 3 Ts"?

**Comment by theodorosploumis** [comment]
> That would be A.10]? Does the task mean that the user should be able to specify for example a limit of "2 Ls and 3 Ts"?

No, still the same rule applies. But you can use the Shape itself even once.

**Comment by MaciejRtk95** [comment]
Sorry, I'm not sure I understand

**Comment by theodorosploumis** [comment]
> Sorry, I'm not sure I understand

You can still use `P` itself as also as any other Shape (but only once) to create a larger `P`.

**Comment by GeorgeFkd** [comment]
Η 4 μας έχει φανεί λίγο ασαφής
Στην ερώτηση 4 τι ακριβώς εννοείτε με locate the shape, ο χρήστης τι
  input θα δίνει, το σχήμα μόνο ή και το πώς έχει περιστραφεί?

Επίσης στην 4 τι επιστρέφει τελικά η συνάρτηση, όλες τις πιθανές
θέσεις, τα allowed positions ή τα positions που βρίσκεται κάθε
instance του σχήματος που ζήτησε?

**Comment by theodorosploumis** [comment]
> Η 4 μας έχει φανεί λίγο ασαφής

Some more details already added on the main Topic question:

_4] Create a function that locates a Shape (rotated/flipped etc) inside a Canvas on any allowed positions. Example: Given a Canvas and a Shape on any option (e.g. `12x5` with `L1`, see Function from Q3) return all the possible positions inside the Canvas this Shape option can be added on._

**Comment by GeorgeFkd** [comment]
Στο μέρος Β στο πρόβλημα 3, μεγαλύτερη περίμετρος με ποιους περιορισμούς(π.χ. με 2 shapes, σε Canvas των τάδε διαστάσεων ? διότι σε έναν τεράστιο καμβά είναι και τεράστιες οι περίμετροι των groups.

**Comment by theodorosploumis** [comment]
> Στο μέρος Β στο πρόβλημα 3, μεγαλύτερη περίμετρος με ποιους περιορισμούς(π.χ. με 2 shapes, σε Canvas των τάδε διαστάσεων ? διότι σε έναν τεράστιο καμβά είναι και τεράστιες οι περίμετροι των groups.

`Group` here is the same as `Congruent Group`. So it is about 2 only Shapes.

**Comment by GeorgeFkd** [comment]
In part D, Q. No 24,25 is it up for creative interpretation? if not, could you provide an example of something you would consider a "symmetric butterfly" and "Tower of Thessaloniki"?

**Comment by theodorosploumis** [comment]
> In part D, Q. No 24,25 is it up for creative interpretation? if not, could you provide an example of something you would consider a "symmetric butterfly" and "Tower of Thessaloniki"?

Yes it is about creativity but you can solve it using all the functions before.

**Comment by theodorosploumis** [comment]
The GitHub topic tag for 2023 is [#serres-hackathon-2023](https://github.com/topics/serres-hackathon-2023). Please add this tag on your GitHub repo. 
See https://stackoverflow.com/a/62767178/1365264.

**Comment by theodorosploumis** [comment]
You can submit your project on https://bit.ly/serreshack-submit-project.

**Comment by theodorosploumis** [comment]
See you next year! :-)
